---
- hosts:  "{{ variable_host | default('test') }}"
  become_method: sudo
  become: yes
  gather_facts: True
  tasks:

# Update and upgrade base OS
  - name: Update packages
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Upgrade all apt packages
    apt:
      upgrade: dist
      force_apt_get: yes

  - name: Check if a reboot is needed for Ubuntu
    stat:
      path: /var/run/reboot-required
    register: reboot_required
    ignore_errors: yes

# Reboot if needed
  - name: Reboot the Debian or Ubuntu server
    reboot:
      msg: "Reboot initiated by Ansible due to kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_required.stat.exists

# Purge old unused kernels
  - name: Purge old kernels
    apt:
      purge: yes
      autoremove: yes

# Install update manager
  - name: Install Update Manager
    apt:
      name: update-manager-core
      state: latest

# Upgrade Versions
  - name: Upgrade OS Version
    shell: do-release-upgrade
      register: version_update

# Reboot into latest lts
  - name: Reboot into LTS
    reboot:
      msg: "Reboot initiated by Ansible due to kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: version_update.stat.exists

