---
# Add DNS records to PiHole container volume
- name: Include variables
  include_vars: pihole_vars.yml

- name: Add the new DNS entries to the PiHole container volume
  lineinfile:
    path: "{{ pihole_path }}"
    state: present
    line: "{{ item }}"
  loop: "{{ vm_ip_list }}"
  delegate_to: "{{ pihole_host}}"
  become: true

- name: Restart the PiHole container
  ansible.builtin.shell:
    cmd: "cd {{ docker_path }} && ls -la && docker-compose down && docker-compose up -d"
  delegate_to: "{{ pihole_host }}"
  become: true