---
# Add DNS records to PiHole container volume
- name: Include variables
  include_vars: pihole_vars.yml

- name: Add the new DNS entries to the PiHole container volume
  lineinfile:
    path: "{{ pihole_path }}"
    state: present
    line: "{{ item }}"
  loop: "{{ vm_ip_list }}"
  delegate_to: "{{ pihole_host}}"
  become: true
  register: dns_record_added
  changed_when: dns_record_added is changed

- name: Restart the PiHole container
  ansible.builtin.shell:
    cmd: "cd {{ docker_path }} && ls -la && docker-compose down && docker-compose up -d"
  delegate_to: "{{ pihole_host }}"
  become: true
  when: dns_record_added.changed

- name: Sleep for 45 seconds to allow PiHole to restart
  ansible.builtin.wait_for:
    timeout: 45
    state: started
    host: "{{ pihole_host }}"
    port: 53
    delay: 5
    connect_timeout: 5
  delegate_to: "{{ pihole_host }}"
  become: true
  when: dns_record_added.changed