---
# Add DNS records to PiHole container volume
- name: Include variables
  include_vars: pihole_vars.yml

- name: Add the new DNS entries to the PiHole container volume
  lineinfile:
    path: "{{ pihole_path }}"
    state: present
    line: "{{ item }}"
  loop: "{{ vm_ip_list }}"
  delegate_to: "{{ pihole_host}}"
  become: true

- name: Restart the PiHole container
  ansible.builtin.shell:
    cmd: "cd {{ docker_path }} && ls -la && docker-compose down && docker-compose up -d"
  delegate_to: "{{ pihole_host }}"
  become: true

- name: Check PiHole container status
  docker_container_info:
    name: pihole
  register: container_info
  until: container_info.container.State.Status == "running"
  retries: 6
  delay: 30

- name: Display result
  debug:
    msg: "Container pihole is running"
  when: container_info.container.State.Status == "running"

- name: Display failure message
  debug:
    msg: "Container pihole is not running after {{ max_retries * 30 }} seconds"
  when: container_info.container.State.Status != "running"