---
# Run the docker role against os_ubuntu hosts
- name: Updating Docker Containers on Ubuntu hosts
  hosts: os_ubuntu
  gather_facts: yes
  remote_user: sa-ansible
  become: yes

  roles:
    - docker