---
# Run the os_updates role against os_ubuntu hosts
- name: Package Updates on Ubuntu hosts
  hosts: os_ubuntu
  gather_facts: yes
  remote_user: sa-ansible
  become: yes

  roles:
    - os_updates