---
    - hosts:  "{{ variable_host | default('winbots') }}"
      name: bootstrap a windows desktop
      gather_facts: yes
      vars_prompt: 
        - name: ansible_password
          prompt: "ansible user password"

      tasks:
        - name: set user password for playbook
          set_fact: ansible_password="{{ ansible_password }}"
  
        - name: touch a logs file
          win_file:
            path: C:\Users\ansible\logs\test.json
            state: touch  

        # - name: write facts to a file
        #   win_lineinfile:
        #     line: "{{ ansible_facts }}" 
        #     path: 'L:\ansible\"{{ ansible_hostname }}".json'
        #     create: yes
        #     state: touch
          