# info to write to file

# "ansible_distribution": "CentOS",
#     "ansible_distribution_file_variety": "RedHat",
#     "ansible_distribution_major_version": "7",
#     "ansible_distribution_release": "Core",
#     "ansible_distribution_version": "7.5.1804",
#     "ansible_dns": {
#         "nameservers": [
#             "127.0.0.1"

# "ansible_eth0": {
#     "active": true,
#     "device": "eth0",
#     "ipv4": {
#         "address": "REDACTED",
#         "netmask": "255.255.255.0",
#         "network": "REDACTED"

# "ansible_hostname": "centos-7-rax-dfw-0003427354"---
---
    - hosts:  "{{ variable_host | default('winbots') }}"
      name: bootstrap a windows desktop
      gather_facts: yes
      vars_prompt: 
        - name: ansible_password
          prompt: "ansible user password"

      tasks:
        - name: set user password for playbook
          set_fact: ansible_password="{{ ansible_password }}"
        
        - name: mount logs drive
          win_mapped_drive:
            letter: L
            path: \\10.10.10.20\logs

        - name: touch a logs file
          win_file:
            path: C:\logs\ansible\test.json
            state: touch  

        - name: write facts to a file
          win_lineinfile:
            line: "{{ ansible_facts }}" 
            path: 'L:\ansible\"{{ ansible_hostname }}".json'
            create: yes
            state: touch
          