---
    - hosts:  "{{ variable_host | default('winbots') }}"
      name: bootstrap a windows desktop
      gather_facts: yes
      vars_prompt: 
        - name: ansible_password
          prompt: "ansible user password"

      tasks:
        - name: set user password for playbook
          set_fact: ansible_password="{{ ansible_password }}"
  
        - name: touch a logs file
          win_file:
            path: C:\Users\ansible\win_hosts.json
            state: touch  

        - name: write facts to a file
          win_lineinfile:
            line: "{{ ansible_hostname }}" 
            path: C:\Users\ansible\win_hosts.json
            create: yes
            state: present

        - name: copy logs to file server
          throttle: 1
          win_copy: 
            src: C:\Users\ansible\win_hosts.json
            dest: \\10.10.10.20\logs
            remote_src: yes
          become: yes
          become_method: runas
          vars:
            ansible_become_user: ansible
            ansible_become_pass: "{{ ansible_password }}"