---
- name: Get VM details from Proxmox API
  uri:
    url: "{{ proxmox_cluster_url }}/api2/json/nodes/{{ item.node }}/qemu/{{ item.vmid }}/agent/network-get-interfaces"
    method: GET
    headers:
      Cookie: "PVEAuthCookie={{ proxmox_ticket.json.data.ticket }}"
      CSRFPreventionToken: "{{ proxmox_ticket.json.data.CSRFPreventionToken }}"
    validate_certs: true
  register: vm_network_info
  loop: "{{ vm_info.proxmox_vms }}"
  failed_when: false
  no_log: true