---
- name: Print ansible_host
  ansible.builtin.debug:
    msg: "ansible_host is {{ ansible_host }}"

- name: Run preupdate tasks
  ansible.builtin.include_tasks: "ubuntu_preupdates.yml"
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Run update tasks
  ansible.builtin.include_tasks: "ubuntu_updates.yml"
  when: ansible_facts['distribution'] == "Ubuntu"