---
- name: Print ansible_host
  ansible.builtin.debug:
    msg: "ansible_host is {{ ansible_host }}"

- name: Check OS type for Ubuntu
  ansible.builtin.include_tasks: "ubuntu_updates.yml"
  when: ansible_facts['distribution'] == "Ubuntu"
