---
- name: Check OS type
  ansible.builtin.include_tasks: "{{ ansible_os_family }}_update.yml"
  vars:
    ansible_os_family: "{{ ansible_facts['os_family'] | lower }}"
  when: ansible_os_family in ['ubuntu', 'debian', 'windows']

- name: Fallback for unsupported OS
  ansible.builtin.fail:
    msg: "Unsupported OS type: {{ ansible_os_family }}"
  when: ansible_os_family not in ['ubuntu', 'debian', 'windows']