---
- name: Update package cache
  ansible.builtin.shell: apt-get update
  register: update_cache

- name: List upgradable packages
  ansible.builtin.shell: apt list --upgradable
  register: upgradable_packages

- name: Print names of packages to be upgraded
  ansible.builtin.debug:
    msg: "{{ upgradable_packages.stdout_lines }}"

- name: Update all packages
  ansible.builtin.shell: apt-get upgrade -y
  register: upgrade_results
  until: upgrade_results is succeeded
  retries: 10
  delay: 10

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Notify reboot is required
  ansible.builtin.debug:
    msg: "Reboot is required for the system to apply all updates."
  when: reboot_required_file.stat.exists