---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: Wait for apt to be available
  shell: |
    timeout=60
    end=$((SECONDS+timeout))
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
      if [ $SECONDS -ge $end ]; then
        echo "Timeout waiting for apt lock"
        exit 1
      fi
      sleep 5
    done

- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    force_apt_get: true
  register: upgrade_results

- name: List upgraded packages
  ansible.builtin.debug:
    msg: "{{ upgrade_results.stdout_lines }}"

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Notify reboot is required
  ansible.builtin.debug:
    msg: "Reboot is required for the system to apply all updates."
  when: reboot_required_file.stat.exists