---
- name: Update package list and check for upgrades
  ansible.builtin.apt:
    update_cache: yes
  register: apt_updates

- name: Print number of packages that can be upgraded
  ansible.builtin.debug:
    msg: "{{ apt_upgrade.packages | length }} packages can be upgraded."

- name: DEBUG - Print available upgrades
  ansible.builtin.debug:
    msg: "{{ apt_upgrade.packages }}"
  when: apt_upgrade.packages | length > 0

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: safe
  when: apt_upgrade.packages | length > 0
  register: apt_upgrade

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Notify reboot is required
  ansible.builtin.debug:
    msg: "Reboot is required for the system to apply all updates."
  when: reboot_required_file.stat.exists