---
- name: Update package list and check for upgrades
  ansible.builtin.apt:
    update_cache: yes
  register: apt_updates

- name: Get list of upgradable packages
  ansible.builtin.shell: apt list --upgradable
  register: upgradable_packages
  changed_when: false
  when: apt_updates.changed or apt_updates.cache_updated

- name: DEBUG - Print available upgrades
  ansible.builtin.debug:
    msg: "{{ upgradable_packages.stdout }}"
  when: apt_updates.packages | length > 0

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: safe
  when: apt_updates.packages | length > 0
  register: apt_upgrade

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Notify reboot is required
  ansible.builtin.debug:
    msg: "Reboot is required for the system to apply all updates."
  when: reboot_required_file.stat.exists