---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true

- name: Wait for apt lock to be released
  ansible.builtin.shell: |
    timeout=60
    end=$((SECONDS+timeout))
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
      if [ $SECONDS -ge $end ]; then
        echo "Timeout waiting for apt lock"
        exit 1
      fi
      sleep 1
    done
  register: wait_for_lock
  failed_when: wait_for_lock.rc != 0
  changed_when: false

- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
  register: upgrade_results
  until: upgrade_results is succeeded
  retries: 10
  delay: 10

- name: List upgraded packages
  ansible.builtin.debug:
    msg: "{{ upgrade_results.stdout_lines }}"

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Notify reboot is required
  ansible.builtin.debug:
    msg: "Reboot is required for the system to apply all updates."
  when: reboot_required_file.stat.exists