--- 
- name: Upgrade all packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    force_apt_get: true
  register: upgrade_results

- name: List upgraded packages
  ansible.builtin.debug:
    msg: "{{ upgrade_results }}"
  when: upgrade_results.changed

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Notify reboot is required
  ansible.builtin.debug:
    msg: "Reboot is required for the system to apply all updates."
  when: reboot_required_file.stat.exists