---
# Precheck validation
- name: Validate new controller node
  become: true
  stat:
    path: /home/{{ k8s_user }}/.kube/config
  register: kube_config_set

- name: Skip pre-configured nodes
  set_fact:
    skip_config: "{{ kube_config_set.stat.exists }}"
  when: kube_config_set.stat.exists

- name: Notify user of existing configuration
  debug:
    msg: "Kubernetes controller already configured. Skipping configuration."
  when: kube_config_set.stat.exists

# Create a new cluster
- name: Initialize k8s controller
  block:
    - name: Initialize Kubernetes cluster
      become: true
      command: >
        kubeadm init 
        --pod-network-cidr=10.244.0.0/16 
        --cri-socket unix:///var/run/containerd/containerd.sock

    - name: Create .kube directory
      become: true
      file:
        path: /home/{{ k8s_user }}/.kube
        state: directory
        mode: '0755'
        owner: "{{ k8s_user }}"
        group: "{{ k8s_user }}"

    - name: Copy admin.conf to user's kube config
      become: true
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ k8s_user }}/.kube/config
        remote_src: true
        owner: "{{ k8s_user }}"
        group: "{{ k8s_user }}"

    - name: Install Flannel network plugin
      shell: 
        cmd: sudo -u {{ k8s_user }} kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

    - name: Get join command
      shell: sudo -u {{ k8s_user }} kubeadm token create --print-join-command
      register: join_command

    - name: Get certificate key
      become: true
      shell: kubeadm init phase upload-certs --upload-certs
      register: certificate_key
 
    # - name: DEBUG - Display join command
    #   debug:
    #     msg: 
    #       join_command: "{{ join_command.stdout }}"
    #       certificate_key: "{{ certificate_key.stdout }}"

    - name: Store join command in AWS SSM Parameter Store
      community.aws.ssm_parameter:
        name: "/ansible/k8s/{{ proxmox_name | regex_replace('\\d+$', '') }}-join-command"
        value: "{{ join_command.stdout }}"
        string_type: SecureString
        region: "us-west-2"
      delegate_to: localhost

    - name: Store certificate key in AWS SSM Parameter Store
      community.aws.ssm_parameter:
        name: "/ansible/k8s/{{ proxmox_name | regex_replace('\\d+$', '') }}-certificate-key"
        value: "{{ certificate_key.stdout }}"
        string_type: SecureString
        region: "us-west-2"
      delegate_to: localhost
  when:
    - ssm_join_result is failed
    - skip_config is not defined

# Join additional controllers
# tasks to be built out with AWS env, after homelab migration to k8s
# - name: Join additional controller to the cluster
#   block:
#     - name: Join the cluster as an additional controller
#       command: "{{ join_command }}"

#     - name: Debug - Display join controller command
#       debug:
#         var: join_command
#   when: ssm_join_result is succeeded
