---
# Precheck validation
- name: Validate new worker node
  become: true
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kube_config_set

- name: Set skip for configured nodes
  set_fact:
    skip_config: "{{ kube_config_set.stat.exists }}"
  when: kube_config_set.stat.exists

- name: Notify user of existing configuration
  debug:
    msg: "Kubernetes worker already configured. Skipping configuration."
  when: kube_config_set.stat.exists

# - name: Check for existing join command in AWS SSM Parameter Store
#   set_fact:
#     ssm_join_command: "{{ lookup('aws_ssm', '/ansible/k8s/' + (proxmox_name | regex_replace('\\d+$', '')) + '-join-command', region='us-west-2', decrypt='true') }}"
#   delegate_to: localhost
#   register: ssm_join_result

# Confirm the join command is valid
- name: Check the join command age and update if needed
  block:
  - name: Get SSM parameter metadata
    community.aws.ssm_parameter:
      name: "/ansible/k8s/{{ proxmox_name | regex_replace('\\d+$', '') }}-join-command"
      region: "us-west-2"
    register: ssm_parameter_info
    delegate_to: localhost

  # - name: DEBUG - Display SSM parameter info
  #   debug:
  #     var: ssm_parameter_info

  - name: Calculate parameter age in hours
    set_fact:
      parameter_age: "{{ ((ansible_date_time.epoch | int) - (ssm_parameter_info.parameter_metadata.last_modified_date | to_datetime('%Y-%m-%dT%H:%M:%S.%fZ') | int) / 3600) }}"

  - name: DEBUG - Display parameter age
    debug:
      msg: "The parameter age is {{ parameter_age }} hours."
# # Add k8s worker nodes to the cluster
# - name: Add new worker to the cluster
#   become: true
#   command: "{{ ssm_join_command }} --cri-socket unix:///var/run/cri-dockerd.sock"
#   when:
#   - ssm_join_result is succeeded
#   - skip_config is not defined

# # Notify if the join command is not found
# - name: Notify user of missing join command
#   debug:
#     msg: "No cluster join command found. Skipping worker configuration."
#   when: ssm_join_result is failed