---
- name: Check for existing join command in AWS SSM Parameter Store
  community.aws.ssm_parameter:
    name: "/ansible/k8s/join-command"
  register: ssm_join_command
  delegate_to: localhost
  ignore_errors: true

- name: Initialize k8s controller
  become_user: sa-k8s
  become: true
  block:
    - name: Initialize Kubernetes cluster
      command: >
        kubeadm init 
        --pod-network-cidr=10.244.0.0/16 
        --cri-socket unix:///var/run/cri-dockerd.sock
      args:
        creates: /tmp/k8s/admin.conf

    - name: Create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /tmp/k8s/admin.conf
        dest: $HOME/.kube/config
        remote_src: true
        owner: "{{ ansible_user }}"

    - name: Install Flannel network plugin
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

    - name: Get join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Store join command in AWS SSM Parameter Store
      community.aws.ssm_parameter:
        name: "/ansible/k8s/join-command"
        value: "{{ join_command.stdout }} --control-plane --certificate-key {{ certificate_key.stdout }}"
        type: String
  when: ssm_join_command.failed or ssm_join_command.parameters | length == 0

- name: Join additional controller to the cluster
  become_user: sa-k8s
  become: true
  block:
    - name: Retrieve join command from AWS SSM Parameter Store
      set_fact:
        join_command: "{{ ssm_join_command.parameters[0].value }}"

    - name: Join the cluster as an additional controller
      command: "{{ join_command }}"
  when: not ssm_join_command.failed and ssm_join_command.parameters | length > 0

- name: Get certificate key
  command: kubeadm init phase upload-certs --upload-certs
  register: certificate_key
  when: ssm_join_command.failed or ssm_join_command.parameters | length == 0

- name: Debug - Display join command
  debug:
    var: join_command
