---
# Precheck validation
- name: Validate new controller node
  become: true
  stat:
    path: /home/{{ k8s_user }}/.kube/config
  register: kube_config_set

- name: Set skip for configured nodes
  set_fact:
    skip_config: "{{ kube_config_set.stat.exists }}"
  when: kube_config_set.stat.exists

- name: Check for existing join command in AWS SSM Parameter Store
  set_fact:
    ssm_join_command: "{{ lookup('aws_ssm', '/ansible/k8s/{{ proxmox_name | regex_replace('\\d+$', '') }}-join-command', region='us-west-2', decrypt='true') }}"
  delegate_to: localhost
  register: ssm_join_result
  ignore_errors: true

# Add k8s worker nodes to the cluster
- name: Add new worker to the cluster
  block:
    - name: Join the Kubernetes cluster
      become: true
      command: "{{ ssm_join_command }}"
  when:
    - ssm_join_result is succeeded
    - not skip_config
