---
# Precheck validation
- name: Validate new worker node
  become: true
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kube_config_set

- name: Set skip for configured nodes
  set_fact:
    skip_config: "{{ kube_config_set.stat.exists }}"
  when: kube_config_set.stat.exists

- name: Notify user of existing configuration
  debug:
    msg: "Kubernetes worker already configured. Skipping configuration."
  when: kube_config_set.stat.exists

- name: Set join command if not already set
  set_fact:
    join_command: "{{ lookup('aws_ssm', '/ansible/k8s/' + (proxmox_name | regex_replace('\\d+$', '')) + '-join-command', region='us-west-2', decrypt='true') }}"
  when: join_command is not defined

# - name: DEBUG - Display join command
#   debug:
#     msg: 
#       join_command: "{{ join_command }}"

# Add k8s worker nodes to the cluster
- name: Add new worker to the cluster
  become: true
  command: "{{ join_command }} --cri-socket unix:///run/containerd/containerd.sock"
  when:
  - skip_config is not defined