---
# Create a k8s cluster user
- name: Create k8s user
  include_role:
    name: common
    tasks_from: create_ubuntu_users.yml

# Configure k8s nodes
- name: Prep k8s nodes
  include_tasks: node_prep.yml

- name: Run k8s controller config
  include_tasks: k8s_controller_config.yml
  when: 
    - "'k8s_controller' in proxmox_tags_parsed"

- name: Run k8s worker config
  include_tasks: k8s_worker_config.yml
  when: 
    - "'k8s_worker' in proxmox_tags_parsed"