---
# Host configs for k8s nodes
- name: Disable swap
  command: swapoff -a

- name: Remove swap /etc/fstab entry
  lineinfile:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    state: absent

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Configure stsctl
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

# Configure containerd
- name: Configure crictl
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml

- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes
  register: containerd_deployed

- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory
  when: containerd_deployed.changed

- name: Set containerd config
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  when: containerd_deployed.changed

- name: Restart containerd service to apply changes
  service:
    name: containerd
    state: restarted
  when: containerd_deployed.changed

# Install required packages
- name: Add k8s apt key
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: 0644
    force: true

- name: Add k8s repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present
    update_cache: yes

- name: Install k8s packages
  apt:
    name: "{{ item }}={{ k8s_version }}.*"
    state: present
    update_cache: yes
  with_items:
    - "{{ k8s_packages }}"

- name: Check if helm is Installed
  command: helm version
  register: helm_check
  ignore_errors: true

- name: Install helm
  when: helm_check.rc != 0
  block:
  - name: Get helm apt key
    get_url:
      url: https://baltocdn.com/helm/signing.asc
      dest: /etc/apt/keyrings/helm.asc
      mode: 0644
      force: true

  - name: Add helm repository
    apt_repository:
      repo: "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
      state: present
      update_cache: yes

- name: Install non-k8s packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ additional_packages }}"

- name: Hold k8s packages at current version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "{{ k8s_packages }}"
