---
# Install required packages
- name: Configure Docker
  include_role: 
    name: common
    tasks_from: docker_setup.yml

- name: Configure CRI-Dockerd
  include_tasks: cri_dockerd_config.yml

- name: Add k8s apt key
  get_url: 
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: 0644
    force: true

- name: Add k8s repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present
    update_cache: yes

- name: Install k8s packages
  apt:
    name: "{{ item }}={{ k8s_version }}.*"
    state: present
    update_cache: yes
  with_items:
    - "{{ k8s_packages }}"

- name: Install non-k8s packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ additional_packages }}"

- name: Hold k8s packages at current version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "{{ k8s_packages }}"

# Host configs for k8s nodes
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap /etc/fstab entry
  lineinfile:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    state: absent

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Configure stsctl
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables