---
# Check for an existing join command in AWS SSM Parameter Store  
- name: Check for existing join command in AWS SSM Parameter Store
  set_fact:
    ssm_join_command: "{{ lookup('aws_ssm', '/ansible/k8s/' + (proxmox_name | regex_replace('\\d+$', '')) + '-join-command', region='us-west-2', decrypt='true') }}"
  delegate_to: localhost
  register: ssm_join_result
  ignore_errors: true

# Confirm the join command is valid
- name: Check the join command age and update if needed
  block:
  - name: Get SSM parameter metadata
    community.aws.ssm_parameter:
      name: "/ansible/k8s/{{ proxmox_name | regex_replace('\\d+$', '') }}-join-command"
      region: "us-west-2"
    register: ssm_parameter_info
    delegate_to: localhost
  
  - name: Generate current date/time in the same format
    shell: "date -u '+%Y-%m-%dT%H:%M:%S.%6N%z'"
    register: current_datetime
    delegate_to: localhost

  - name: Calculate parameter age in hours
    set_fact:
      parameter_age: "{{ ((current_datetime.stdout | to_datetime('%Y-%m-%dT%H:%M:%S.%f%z')).timestamp() - (ssm_parameter_info.parameter_metadata.last_modified_date | to_datetime('%Y-%m-%dT%H:%M:%S.%f%z')).timestamp()) / 3600 | int }}"

  # - name: DEBUG - Display parameter age
  #   debug:
  #     msg: 
  #     - "The parameter age is {{ parameter_age }} hours."
  #     - "ansible date time: {{ current_datetime.stdout | to_datetime('%Y-%m-%dT%H:%M:%S.%f%z') }}"
  #     - "raw last modified date: {{ ssm_parameter_info.parameter_metadata.last_modified_date | to_datetime('%Y-%m-%dT%H:%M:%S.%f%z') }}"
  when: ssm_join_result is succeeded

- name: Update the join command if older than 24 hours
  block:
  - name: Get join command
    shell: sudo -u {{ k8s_user }} kubeadm token create --print-join-command
    register: join_command

  - name: Get certificate key
    become: true
    shell: kubeadm init phase upload-certs --upload-certs
    register: certificate_key

  # - name: DEBUG - Display join command
  #   debug:
  #     msg: 
  #       join_command: "{{ join_command.stdout }}"
  
  - name: Store join command in AWS SSM Parameter Store
    community.aws.ssm_parameter:
      name: "/ansible/k8s/{{ proxmox_name | regex_replace('\\d+$', '') }}-join-command"
      value: "{{ join_command.stdout }}"
      string_type: SecureString
      region: "us-west-2"
    delegate_to: localhost
  when: 
    - parameter_age > 24
    - ssm_join_result is succeeded

- name: Set join command if less that 24 hours
  set_fact:
    join_command: "{{ ssm_join_command }}"
  when: 
    - parameter_age <= 24
    - ssm_join_result is succeeded