---
- hosts:  "{{ variable_host | default('winbots') }}"
  gather_facts: no
  vars_prompt: 
    - name: ansible_password
      prompt: "ansible user password"
      
  tasks:
  - name: Search for updates, write to a file if they are found
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates 
      stage: searched
      log_path: C:\ansible_wu.txt
    ignore_errors: yes
      
  - name: Install all critical and security updates
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      state: installed
    register: update_result
    ignore_errors: yes

  - name: Reboot host if required
    win_reboot:
    when: update_result.reboot_required