---
# Run a play against proxmox_all_running hosts and gather facts
- name: Filtering for Ubuntu hosts
  hosts: os_ubuntu
  gather_facts: yes
  remote_user: sa-ansible

  roles:
    - os_updates