# info to write to file

# "ansible_distribution": "CentOS",
#     "ansible_distribution_file_variety": "RedHat",
#     "ansible_distribution_major_version": "7",
#     "ansible_distribution_release": "Core",
#     "ansible_distribution_version": "7.5.1804",
#     "ansible_dns": {
#         "nameservers": [
#             "127.0.0.1"

# "ansible_eth0": {
#     "active": true,
#     "device": "eth0",
#     "ipv4": {
#         "address": "REDACTED",
#         "netmask": "255.255.255.0",
#         "network": "REDACTED"

# "ansible_hostname": "centos-7-rax-dfw-0003427354"
---
    - hosts:  "{{ variable_host | default('bots') }}"
      become_method: sudo
      become: yes
      gather_facts: true
      tasks:
        - name: print host gather_facts
          debug: 
            var: ansible_facts
        - name: write facts to a file
          lineinfile:
            line: "{{ item }}"
            path: /tmp/ansible_fact_details.json
            loop:
              - "ansible_hostname"
