---
    - hosts:  "{{ variable_host | default('bots') }}"
      become_method: sudo
      become: yes
      gather_facts: true
      tasks:
        - name: Validate NFS is installed
          apt:
            name: nfs-common
            state: present
        - name: Mount Logs NFS
          mount:
            src: 10.10.10.20:/mnt/ZPool02/logs
            path: /logs
            opts: rw,sync,hard,intr
            state: mounted
            fstype: nfs
        - name: write facts to a file
          lineinfile:
            line: "{{ item }}"
            path: /logs/ansible/{{ ansible_hostname }}/endpoint_details.json
            create: yes
            state: present
          become: yes
          loop:
            - "Hostname: {{ ansible_hostname }}"
            - "IP: {{ ansible_default_ipv4.address }}"
            - "Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}"
        - name: Unmount Logs
          mount:
            path: /logs
            state: unmounted
