---
- hosts:  "{{ variable_host | default('bots') }}"
  become_method: sudo
  become: yes
  gather_facts: no
  tasks:

# Update and upgrade base OS
  - name: Update packages
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600

  - name: Upgrade all apt packages
    apt: 
      upgrade: dist 
      force_apt_get: yes

  - name: Check if a reboot is needed for Ubuntu
    stat: 
      path: /var/run/reboot-required 
    register: results
    changed_when: results.stat.exists
    ignore_errors: yes
    notify: restart-required
  
  handlers:
 # reboot hosts that were updated
  - name: Reboot required hosts
    shell: reboot
    async: 30
    poll: 0
    listen: restart-required

  - name: Waiting for hosts to start up
    wait_for_connection:
      delay: 30
      connect_timeout: 10
      sleep: 10
      timeout: 300
    listen: restart-required

