---
- hosts:  "{{ variable_host | default('bots') }}"
  name: bootstrap a windows desktop
  vars_prompt: 
    - name: ansible_password
      prompt: "ansible user password"
    - name: target_user
      prompt: "target user"

  tasks:
  - name: set user password for playbook
    set_fact: ansible_password="{{ ansible_password }}"
  - name: set target user profile 
    set_fact: target_user="{{ target_user }}"

- name: updateOS
  import_playbook: plays/ubuntu/updateOS.yml