---
- hosts:  "{{ variable_host | default('winbots') }}"
  become_method: runas
  gather_facts: no
  tasks:
  - name: Copy wsl script to target host
    win_copy:
      src: ~/ansible/psScripts/enableWSL2.ps1
      dest: C:\Users\ansible\Documents\enableWSL2.ps1

  - name: enable WSL2
    win_shell: C:\Users\ansible\Documents\enableWSL2.ps1
    become: yes
    become_user: Administrator

  - name: Reboot host
    win_reboot:
      reboot_timeout: 1200

  - name: install Ubuntu 20.04 LTS
    win_chocolatey:
      name: wsl-ubuntu-2004
      state: present
    bescome_user: "{{ target_user }}"
    become: yes
    
